using System.Text;
using RepoSummary.Models;

namespace RepoSummary.Services;

/// <summary>Builds shareable/exportable artifacts from an analysis: a Markdown summary and
/// an embeddable SVG grade badge. Pure and unit-testable.</summary>
public static class ExportBuilder
{
    /// <summary>A self-contained Markdown summary of the analysis, ready to download.</summary>
    public static string ToMarkdown(GitHubRepoAnalysisResult r)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# {r.FullName}");
        sb.AppendLine();
        if (!string.IsNullOrWhiteSpace(r.Description)) sb.AppendLine($"> {r.Description}").AppendLine();

        if (r.Maturity is not null)
            sb.AppendLine($"**Maturity:** {r.Maturity.Grade} ({r.Maturity.Score}/100)").AppendLine();

        sb.AppendLine("## Overview").AppendLine();
        sb.AppendLine($"- **Stars:** {r.Stars:N0} · **Forks:** {r.Forks:N0} · **Open issues:** {r.OpenIssues:N0}");
        if (!string.IsNullOrEmpty(r.PrimaryLanguage)) sb.AppendLine($"- **Primary language:** {r.PrimaryLanguage}");
        if (!string.IsNullOrEmpty(r.License)) sb.AppendLine($"- **License:** {r.License}");
        if (!string.IsNullOrEmpty(r.ArchitecturePattern)) sb.AppendLine($"- **Architecture:** {r.ArchitecturePattern}");
        if (!string.IsNullOrEmpty(r.DatabaseTech)) sb.AppendLine($"- **Database:** {r.DatabaseTech}");
        if (r.TestFileCount > 0) sb.AppendLine($"- **Tests:** {r.TestFileCount} file(s){(string.IsNullOrEmpty(r.TestFramework) ? "" : $" · {r.TestFramework}")}");
        sb.AppendLine();

        if (r.Languages.Count > 0)
        {
            sb.AppendLine("## Languages").AppendLine();
            foreach (var l in r.Languages.Take(10)) sb.AppendLine($"- {l.Name} — {l.Percentage}%");
            sb.AppendLine();
        }

        if (r.Packages.Count > 0)
        {
            sb.AppendLine("## Key dependencies").AppendLine();
            sb.AppendLine(string.Join(", ", r.Packages.Select(p => p.Name).Distinct().Take(30)));
            sb.AppendLine();
        }

        if (r.ResumeAngles.Count > 0)
        {
            sb.AppendLine("## Résumé angles").AppendLine();
            foreach (var a in r.ResumeAngles) sb.AppendLine($"- {a.Text}");
            sb.AppendLine();
        }

        if (r.InterviewTalkingPoints.Count > 0)
        {
            sb.AppendLine("## Interview talking points").AppendLine();
            foreach (var p in r.InterviewTalkingPoints) sb.AppendLine($"- {p.Text}");
            sb.AppendLine();
        }

        sb.AppendLine("---");
        sb.AppendLine("_Generated by RepoSummary — evidence-backed project summaries._");
        return sb.ToString();
    }

    private static readonly Dictionary<string, string> GradeColor = new()
    {
        ["A"] = "#1a7f37", ["B"] = "#2da44e", ["C"] = "#bf8700", ["D"] = "#bc4c00", ["F"] = "#cf222e",
    };

    /// <summary>A shields-style SVG badge showing the maturity grade, for embedding in a README.</summary>
    public static string BadgeSvg(string? grade, int? score)
    {
        var g = string.IsNullOrEmpty(grade) ? "?" : grade!;
        var color = GradeColor.TryGetValue(g, out var c) ? c : "#8b949e";
        var msg = score is > 0 ? $"{g} · {score}" : g;
        var label = "RepoSummary";

        // Rough width estimate (7px/char) so the two halves fit their text.
        int labelW = 12 + label.Length * 7;
        int msgW = 12 + msg.Length * 7;
        int total = labelW + msgW;
        int labelMid = labelW / 2;
        int msgMid = labelW + msgW / 2;

        return
            $"<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"{total}\" height=\"20\" role=\"img\" aria-label=\"{label}: {msg}\">" +
            $"<rect rx=\"3\" width=\"{total}\" height=\"20\" fill=\"#555\"/>" +
            $"<rect rx=\"3\" x=\"{labelW}\" width=\"{msgW}\" height=\"20\" fill=\"{color}\"/>" +
            $"<rect x=\"{labelW}\" width=\"6\" height=\"20\" fill=\"{color}\"/>" +
            "<g fill=\"#fff\" text-anchor=\"middle\" font-family=\"Verdana,DejaVu Sans,sans-serif\" font-size=\"11\">" +
            $"<text x=\"{labelMid}\" y=\"14\">{label}</text>" +
            $"<text x=\"{msgMid}\" y=\"14\">{Escape(msg)}</text>" +
            "</g></svg>";
    }

    private static string Escape(string s) =>
        s.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
}
